version: "3.9"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    depends_on:
      - postgres
    ports:
      - "8080:3000"
    env_file: backend/.env
  
  postgres: 
    image: postgres:14.3
    ports:
      - "5432:5432"
    env_file: backend/.env